server.port=8000
spring.application.name=products
server.servlet.context-path=/products/api
server.context-path=${server.servlet.context-path}

# spring jpa config
spring.jpa.show-sql=false
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

## DB hikari config
spring.datasource.hikari.minimum-idle=${DATABASE_MIN_IDLE:2}
spring.datasource.hikari.maximum-pool-size=${DATABASE_MAX_CONNECTIONS:3}
spring.jpa.properties.hibernate.default_schema=${DATABASE_SCHEME:public}

# DB config
spring.datasource.url=${APP_DB_DSN:jdbc:postgresql://localhost:5432/linktic_products}
spring.datasource.username=${APP_DB_USER:postgres}
spring.datasource.password=${APP_DB_PASSWORD:postgres}

# Documentation
springdoc.api-docs.path=/doc.json